# Generated by Django 5.1.7 on 2025-03-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlinjectedWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuspiciousWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
