# Generated by Django 5.1.4 on 2025-03-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phishingapp', '0003_enquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='phone',
        ),
    ]
